# This is a basic workflow to help you get started with Actions

name: build and publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [build]
  pull_request:
    branches: [build]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  node_modules:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Runs a single command using the runners shell
      - name: install
        run: yarn

      - name: archive
        run: tar -zcvf node_modules.tar.gz node_modules

      - uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules.tar.gz

  test:
    needs: node_modules
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - uses: actions/download-artifact@v2
        with:
          name: node_modules

      - name: extract
        run: tar -zxvf node_modules.tar.gz

      # Runs a single command using the runners shell
      - name: test
        run: yarn test

  # This workflow contains a single job called "build"
  build:
    needs: node_modules
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - uses: actions/download-artifact@v2
        with:
          name: node_modules

      - name: extract
        run: tar -zxvf node_modules.tar.gz

      # Runs a single command using the runners shell
      - name: build
        run: yarn build

      # Runs a single command using the runners shell
      - name: deploy
        run: yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
